routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/leaderboard', App\Http\Controllers\LeaderboardController::class)->name('leaderboard');

Route::get('/game', [App\Http\Controllers\GameController::class, 'create']);
Route::post('/game', [App\Http\Controllers\GameController::class, 'store']);

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;

    protected $fillable = [
        'correct',
        'total',
    ];

    protected static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            $model->score_percentage = $model->correct / $model->total * 100;
        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function games(): HasMany
    {
        return $this->hasMany(Game::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreGameRequest;
use DOMDocument;
use DOMXPath;

class GameController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Scrapes the movie data and returns the questions and answers for the specified number of rounds.
     */
    public function create(): \Illuminate\Http\JsonResponse
    {
        libxml_use_internal_errors(true);
        $dom = new DOMDocument();
        $dom->loadHtmlFile(config('mnt.IMDB_URL'));
        $xpath = new DOMXPath($dom);
        $nodes = $xpath->query('//td[@class="titleColumn"]');

        $questions = collect();

        foreach ($nodes as $node) {
            $title = $node->getElementsByTagName('a')->item(0)->nodeValue;
            $year = (int) trim($node->getElementsByTagName('span')->item(0)->nodeValue, '()');
            $answers = [['answer' => $year, 'correct' => true]];

            //Generate random years around the correct year
            $range = range($year - 10, $year + 10);
            unset($range[10]);

            foreach (collect($range)->random(3) as $year) {
                $answers[] = ['answer' => $year, 'correct' => false];
            }

            shuffle($answers); //Ensure true answer is not always in the same position

            $questions->push([
                'question' => "When was {$title} released?",
                'answers' => $answers,
            ]);
        }

        return response()->json($questions->random(config('mnt.rounds')));
    }

    /**
     * Store the results of a completed game, returning the score as a string.
     */
    public function store(StoreGameRequest $request): \Illuminate\Http\JsonResponse
    {
        $game = auth()->user()->games()->create($request->validated());
        $score = $game->correct * config('mnt.correct_points');
        $score = $score + ($game->total - $game->correct) * config('mnt.incorrect_points');
        $scoreMax = $game->total * config('mnt.correct_points');

        return response()->json("{$score}/{$scoreMax} ({$game->score_percentage}%)", 201);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(): \Illuminate\View\View
    {
        return view('home');
    }
}

app/Http/Controllers/LeaderboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;

class LeaderboardController extends Controller
{
    public function __invoke()
    {
        $users = User::withCount('games')
            ->withAvg('games', 'score_percentage')
            ->limit(10)
            ->orderBy('games_avg_score_percentage', 'DESC')
            ->get();

        return view('leaderboard', compact('users'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <game/>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Movie Night Trivia') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Movie Night Trivia') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <a class="nav-link" href="{{ route('leaderboard') }}">Leaderboard</a>
                      </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
          @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/leaderboard.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col" class="text-right">Average Score (%)</th>
                  <th scope="col" class="text-right">Total Games Played</th>
                </tr>
              </thead>
              <tbody>
              @foreach ($users as $user)
                <tr>
                  <th scope="row">{{ $loop->iteration }}</th>
                  <td>{{ $user->name }}</td>
                  <td class="text-right">{{ round($user->games_avg_score_percentage) }}</td>
                  <td class="text-right">{{ $user->games_count }}</td>
                </tr>
              @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection